### ISSUE TITLE
I  can not  find  "github.com/eapache/go-resiliency/breaker",can  you   give me a link  

### ISSUE THREAD

**Issue by zs1503** [Shopify/sarama#1136] opened 2018-07-18 03:27 UTC
I  can not  find  "github.com/eapache/go-resiliency/breaker",can  you   give me a link

**Comment by eapache** [comment] 2018-07-27 17:56
Duplicate of https://github.com/Shopify/sarama/issues/1135.

**Closed by eapache** 2018-07-27 17:56 UTC
