### ISSUE TITLE
Test Failing

### ISSUE THREAD

**Issue by abjsaha** [Shopify/sarama#1097] opened 2018-05-02 18:50 UTC
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.16.0
Kafka Version: N/a
Go Version: go version go1.10 linux/amd64

##### Configuration

What configuration values are you using for Sarama and Kafka?
None, just building tests.

##### Logs

```
=== RUN   TestProduceRequest
--- FAIL: TestProduceRequest (0.00s)
	request_test.go:76: Decoded request "one record" does not match the encoded one
		encoded: <*>(0xc4201eb020){TransactionalID:<nil> RequiredAcks:291 Timeout:1092 Version:3 records:map[topic:map[173:{recordsType:2 msgSet:<nil> recordBatch:<*>(0xc42039a500){FirstOffset:0 PartitionLeaderEpoch:0 Version:2 Codec:0 Control:false LastOffsetDelta:1 FirstTimestamp:2016-11-22 20:49:55 +0000 UTC MaxTimestamp:1970-01-01 00:00:00 +0000 UTC ProducerID:0 ProducerEpoch:0 FirstSequence:0 Records:[<*>(0xc420216e00){Attributes:0 TimestampDelta:5ms OffsetDelta:0 Key:[1 2 3 4] Value:[5 6 7] Headers:[<*>(0xc42008dd70){Key:[8 9 10] Value:[11 12]}] length:{startOffset:0 length:20}}] PartialTrailingRecord:false compressedRecords:[40 0 10 0 8 1 2 3 4 6 5 6 7 2 6 8 9 10 4 11 12] recordsLen:21}}]]}
		decoded: <*>(0xc4201eb300){TransactionalID:<nil> RequiredAcks:291 Timeout:1092 Version:3 records:map[topic:map[173:{recordsType:2 msgSet:<nil> recordBatch:<*>(0xc42039a640){FirstOffset:0 PartitionLeaderEpoch:0 Version:2 Codec:0 Control:false LastOffsetDelta:1 FirstTimestamp:2016-11-22 20:49:55 +0000 UTC MaxTimestamp:1970-01-01 00:00:00 +0000 UTC ProducerID:0 ProducerEpoch:0 FirstSequence:0 Records:[<*>(0xc420216e70){Attributes:0 TimestampDelta:5ms OffsetDelta:0 Key:[1 2 3 4] Value:[5 6 7] Headers:[<*>(0xc42008def0){Key:[8 9 10] Value:[11 12]}] length:{startOffset:0 length:20}}] PartialTrailingRecord:false compressedRecords:<nil> recordsLen:21}}]]}
```

##### Problem Description
TestProduceRequest Failing

**Comment by eapache** [comment] 2018-05-03 17:33
This looks like a duplicate of #1061 which I still can't really reproduce. If you could compare notes with the author of that ticket and help me figure out what's wrong that would be appreciated.

**Closed by eapache** 2018-05-03 17:33 UTC
