### ISSUE TITLE
valyala Error

### ISSUE THREAD

**Issue by aresetian** [Shopify/sarama#259] opened 2015-02-11 13:42 UTC
When I execute this command __go get github.com/Shopify/sarama__, I  dont have any problem in my project(This download normal) , but when I execute __go build__ in my project (I am import sarama ""github.com/Shopify/sarama" in my code) I get the next result(My Machine  is MAC 10.10.1) :

# github.com/valyala/ybc/bindings/go/ybc
gcc did not produce error at completed:1
on input:
#line 15 "&GOPATH/src/github.com/valyala/ybc/bindings/go/ybc/ybc.go"

#include "ybc_go_glue.c"
#include <stdlib.h> // free

#include <stddef.h> /* for ptrdiff_t and size_t below */

/* Define intgo when compiling with GCC.  */
typedef ptrdiff_t intgo;

typedef struct { char *p; intgo n; } _GoString_;
typedef struct { char *p; intgo n; intgo c; } _GoBytes_;
_GoString_ GoString(char *p);
_GoString_ GoStringN(char *p, int l);
_GoBytes_ GoBytes(void *p, int n);
char *CString(_GoString_);
void *_CMalloc(size_t);
#line 1 "not-declared"
void __cgo_f_1_1(void) { __typeof__(CString) *__cgo_undefined__; }
#line 1 "not-type"
void __cgo_f_1_2(void) { CString *__cgo_undefined__; }
#line 1 "not-const"
void __cgo_f_1_3(void) { enum { __cgo__undefined__ = (CString)*1 }; }
#line 2 "not-declared"
void __cgo_f_2_1(void) { __typeof__(GoBytes) *__cgo_undefined__; }
#line 2 "not-type"
void __cgo_f_2_2(void) { GoBytes *__cgo_undefined__; }
#line 2 "not-const"
void __cgo_f_2_3(void) { enum { __cgo__undefined__ = (GoBytes)*1 }; }
#line 3 "not-declared"
void __cgo_f_3_1(void) { __typeof__(YBC_DE_NOTFOUND) *__cgo_undefined__; }
#line 3 "not-type"
void __cgo_f_3_2(void) { YBC_DE_NOTFOUND *__cgo_undefined__; }
#line 3 "not-const"
void __cgo_f_3_3(void) { enum { __cgo__undefined__ = (YBC_DE_NOTFOUND)*1 }; }
#line 4 "not-declared"
void __cgo_f_4_1(void) { __typeof__(YBC_DE_SUCCESS) *__cgo_undefined__; }
#line 4 "not-type"
void __cgo_f_4_2(void) { YBC_DE_SUCCESS *__cgo_undefined__; }
#line 4 "not-const"
void __cgo_f_4_3(void) { enum { __cgo__undefined__ = (YBC_DE_SUCCESS)*1 }; }
#line 5 "not-declared"
void __cgo_f_5_1(void) { __typeof__(YBC_DE_WOULDBLOCK) *__cgo_undefined__; }
#line 5 "not-type"
void __cgo_f_5_2(void) { YBC_DE_WOULDBLOCK *__cgo_undefined__; }
#line 5 "not-const"
void __cgo_f_5_3(void) { enum { __cgo__undefined__ = (YBC_DE_WOULDBLOCK)*1 }; }
#line 6 "not-declared"
void __cgo_f_6_1(void) { __typeof__(free) *__cgo_undefined__; }
#line 6 "not-type"
void __cgo_f_6_2(void) { free *__cgo_undefined__; }
#line 6 "not-const"
void __cgo_f_6_3(void) { enum { __cgo__undefined__ = (free)*1 }; }
#line 7 "not-declared"
void __cgo_f_7_1(void) { __typeof__(go_commit_item_and_value) *__cgo_undefined__; }
#line 7 "not-type"
void __cgo_f_7_2(void) { go_commit_item_and_value *__cgo_undefined__; }
#line 7 "not-const"
void __cgo_f_7_3(void) { enum { __cgo__undefined__ = (go_commit_item_and_value)*1 }; }
#line 8 "not-declared"
void __cgo_f_8_1(void) { __typeof__(go_get_item_and_value) *__cgo_undefined__; }
#line 8 "not-type"
void __cgo_f_8_2(void) { go_get_item_and_value *__cgo_undefined__; }
#line 8 "not-const"
void __cgo_f_8_3(void) { enum { __cgo__undefined__ = (go_get_item_and_value)*1 }; }
#line 9 "not-declared"
void __cgo_f_9_1(void) { __typeof__(go_get_item_and_value_de_async) *__cgo_undefined__; }
#line 9 "not-type"
void __cgo_f_9_2(void) { go_get_item_and_value_de_async *__cgo_undefined__; }
#line 9 "not-const"
void __cgo_f_9_3(void) { enum { __cgo__undefined__ = (go_get_item_and_value_de_async)*1 }; }
#line 10 "not-declared"
void __cgo_f_10_1(void) { __typeof__(go_set_item_and_value) *__cgo_undefined__; }
#line 10 "not-type"
void __cgo_f_10_2(void) { go_set_item_and_value *__cgo_undefined__; }
#line 10 "not-const"
void __cgo_f_10_3(void) { enum { __cgo__undefined__ = (go_set_item_and_value)*1 }; }
#line 11 "not-declared"
void __cgo_f_11_1(void) { __typeof__(int) *__cgo_undefined__; }
#line 11 "not-type"
void __cgo_f_11_2(void) { int *__cgo_undefined__; }
#line 11 "not-const"
void __cgo_f_11_3(void) { enum { __cgo__undefined__ = (int)*1 }; }
#line 12 "not-declared"
void __cgo_f_12_1(void) { __typeof__(size_t) *__cgo_undefined__; }
#line 12 "not-type"
void __cgo_f_12_2(void) { size_t *__cgo_undefined__; }
#line 12 "not-const"
void __cgo_f_12_3(void) { enum { __cgo__undefined__ = (size_t)*1 }; }
#line 13 "not-declared"
void __cgo_f_13_1(void) { __typeof__(uint64_t) *__cgo_undefined__; }
#line 13 "not-type"
void __cgo_f_13_2(void) { uint64_t *__cgo_undefined__; }
#line 13 "not-const"
void __cgo_f_13_3(void) { enum { __cgo__undefined__ = (uint64_t)*1 }; }
#line 14 "not-declared"
void __cgo_f_14_1(void) { __typeof__(ybc_clear) *__cgo_undefined__; }
#line 14 "not-type"
void __cgo_f_14_2(void) { ybc_clear *__cgo_undefined__; }
#line 14 "not-const"
void __cgo_f_14_3(void) { enum { __cgo__undefined__ = (ybc_clear)*1 }; }
#line 15 "not-declared"
void __cgo_f_15_1(void) { __typeof__(ybc_close) *__cgo_undefined__; }
#line 15 "not-type"
void __cgo_f_15_2(void) { ybc_close *__cgo_undefined__; }
#line 15 "not-const"
void __cgo_f_15_3(void) { enum { __cgo__undefined__ = (ybc_close)*1 }; }
#line 16 "not-declared"
void __cgo_f_16_1(void) { __typeof__(ybc_config_destroy) *__cgo_undefined__; }
#line 16 "not-type"
void __cgo_f_16_2(void) { ybc_config_destroy *__cgo_undefined__; }
#line 16 "not-const"
void __cgo_f_16_3(void) { enum { __cgo__undefined__ = (ybc_config_destroy)*1 }; }
#line 17 "not-declared"
void __cgo_f_17_1(void) { __typeof__(ybc_config_disable_overwrite_protection) *__cgo_undefined__; }
#line 17 "not-type"
void __cgo_f_17_2(void) { ybc_config_disable_overwrite_protection *__cgo_undefined__; }
#line 17 "not-const"
void __cgo_f_17_3(void) { enum { __cgo__undefined__ = (ybc_config_disable_overwrite_protection)*1 }; }
#line 18 "not-declared"
void __cgo_f_18_1(void) { __typeof__(ybc_config_get_size) *__cgo_undefined__; }
#line 18 "not-type"
void __cgo_f_18_2(void) { ybc_config_get_size *__cgo_undefined__; }
#line 18 "not-const"
void __cgo_f_18_3(void) { enum { __cgo__undefined__ = (ybc_config_get_size)*1 }; }
#line 19 "not-declared"
void __cgo_f_19_1(void) { __typeof__(ybc_config_init) *__cgo_undefined__; }
#line 19 "not-type"
void __cgo_f_19_2(void) { ybc_config_init *__cgo_undefined__; }
#line 19 "not-const"
void __cgo_f_19_3(void) { enum { __cgo__undefined__ = (ybc_config_init)*1 }; }
#line 20 "not-declared"
void __cgo_f_20_1(void) { __typeof__(ybc_config_set_data_file) *__cgo_undefined__; }
#line 20 "not-type"
void __cgo_f_20_2(void) { ybc_config_set_data_file *__cgo_undefined__; }
#line 20 "not-const"
void __cgo_f_20_3(void) { enum { __cgo__undefined__ = (ybc_config_set_data_file)*1 }; }
#line 21 "not-declared"
void __cgo_f_21_1(void) { __typeof__(ybc_config_set_data_file_size) *__cgo_undefined__; }
#line 21 "not-type"
void __cgo_f_21_2(void) { ybc_config_set_data_file_size *__cgo_undefined__; }
#line 21 "not-const"
void __cgo_f_21_3(void) { enum { __cgo__undefined__ = (ybc_config_set_data_file_size)*1 }; }
#line 22 "not-declared"
void __cgo_f_22_1(void) { __typeof__(ybc_config_set_de_hashtable_size) *__cgo_undefined__; }
#line 22 "not-type"
void __cgo_f_22_2(void) { ybc_config_set_de_hashtable_size *__cgo_undefined__; }
#line 22 "not-const"
void __cgo_f_22_3(void) { enum { __cgo__undefined__ = (ybc_config_set_de_hashtable_size)*1 }; }
#line 23 "not-declared"
void __cgo_f_23_1(void) { __typeof__(ybc_config_set_hot_data_size) *__cgo_undefined__; }
#line 23 "not-type"
void __cgo_f_23_2(void) { ybc_config_set_hot_data_size *__cgo_undefined__; }
#line 23 "not-const"
void __cgo_f_23_3(void) { enum { __cgo__undefined__ = (ybc_config_set_hot_data_size)*1 }; }
#line 24 "not-declared"
void __cgo_f_24_1(void) { __typeof__(ybc_config_set_hot_items_count) *__cgo_undefined__; }
#line 24 "not-type"
void __cgo_f_24_2(void) { ybc_config_set_hot_items_count *__cgo_undefined__; }
#line 24 "not-const"
void __cgo_f_24_3(void) { enum { __cgo__undefined__ = (ybc_config_set_hot_items_count)*1 }; }
#line 25 "not-declared"
void __cgo_f_25_1(void) { __typeof__(ybc_config_set_index_file) *__cgo_undefined__; }
#line 25 "not-type"
void __cgo_f_25_2(void) { ybc_config_set_index_file *__cgo_undefined__; }
#line 25 "not-const"
void __cgo_f_25_3(void) { enum { __cgo__undefined__ = (ybc_config_set_index_file)*1 }; }
#line 26 "not-declared"
void __cgo_f_26_1(void) { __typeof__(ybc_config_set_max_items_count) *__cgo_undefined__; }
#line 26 "not-type"
void __cgo_f_26_2(void) { ybc_config_set_max_items_count *__cgo_undefined__; }
#line 26 "not-const"
void __cgo_f_26_3(void) { enum { __cgo__undefined__ = (ybc_config_set_max_items_count)*1 }; }
#line 27 "not-declared"
void __cgo_f_27_1(void) { __typeof__(ybc_config_set_sync_interval) *__cgo_undefined__; }
#line 27 "not-type"
void __cgo_f_27_2(void) { ybc_config_set_sync_interval *__cgo_undefined__; }
#line 27 "not-const"
void __cgo_f_27_3(void) { enum { __cgo__undefined__ = (ybc_config_set_sync_interval)*1 }; }
#line 28 "not-declared"
void __cgo_f_28_1(void) { __typeof__(ybc_get_size) *__cgo_undefined__; }
#line 28 "not-type"
void __cgo_f_28_2(void) { ybc_get_size *__cgo_undefined__; }
#line 28 "not-const"
void __cgo_f_28_3(void) { enum { __cgo__undefined__ = (ybc_get_size)*1 }; }
#line 29 "not-declared"
void __cgo_f_29_1(void) { __typeof__(ybc_item_get_size) *__cgo_undefined__; }
#line 29 "not-type"
void __cgo_f_29_2(void) { ybc_item_get_size *__cgo_undefined__; }
#line 29 "not-const"
void __cgo_f_29_3(void) { enum { __cgo__undefined__ = (ybc_item_get_size)*1 }; }
#line 30 "not-declared"
void __cgo_f_30_1(void) { __typeof__(ybc_item_release) *__cgo_undefined__; }
#line 30 "not-type"
void __cgo_f_30_2(void) { ybc_item_release *__cgo_undefined__; }
#line 30 "not-const"
void __cgo_f_30_3(void) { enum { __cgo__undefined__ = (ybc_item_release)*1 }; }
#line 31 "not-declared"
void __cgo_f_31_1(void) { __typeof__(ybc_item_remove) *__cgo_undefined__; }
#line 31 "not-type"
void __cgo_f_31_2(void) { ybc_item_remove *__cgo_undefined__; }
#line 31 "not-const"
void __cgo_f_31_3(void) { enum { __cgo__undefined__ = (ybc_item_remove)*1 }; }
#line 32 "not-declared"
void __cgo_f_32_1(void) { __typeof__(ybc_item_set) *__cgo_undefined__; }
#line 32 "not-type"
void __cgo_f_32_2(void) { ybc_item_set *__cgo_undefined__; }
#line 32 "not-const"
void __cgo_f_32_3(void) { enum { __cgo__undefined__ = (ybc_item_set)*1 }; }
#line 33 "not-declared"
void __cgo_f_33_1(void) { __typeof__(ybc_open) *__cgo_undefined__; }
#line 33 "not-type"
void __cgo_f_33_2(void) { ybc_open *__cgo_undefined__; }
#line 33 "not-const"
void __cgo_f_33_3(void) { enum { __cgo__undefined__ = (ybc_open)*1 }; }
#line 34 "not-declared"
void __cgo_f_34_1(void) { __typeof__(ybc_remove) *__cgo_undefined__; }
#line 34 "not-type"
void __cgo_f_34_2(void) { ybc_remove *__cgo_undefined__; }
#line 34 "not-const"
void __cgo_f_34_3(void) { enum { __cgo__undefined__ = (ybc_remove)*1 }; }
#line 35 "not-declared"
void __cgo_f_35_1(void) { __typeof__(ybc_set_txn_begin) *__cgo_undefined__; }
#line 35 "not-type"
void __cgo_f_35_2(void) { ybc_set_txn_begin *__cgo_undefined__; }
#line 35 "not-const"
void __cgo_f_35_3(void) { enum { __cgo__undefined__ = (ybc_set_txn_begin)*1 }; }
#line 36 "not-declared"
void __cgo_f_36_1(void) { __typeof__(ybc_set_txn_commit) *__cgo_undefined__; }
#line 36 "not-type"
void __cgo_f_36_2(void) { ybc_set_txn_commit *__cgo_undefined__; }
#line 36 "not-const"
void __cgo_f_36_3(void) { enum { __cgo__undefined__ = (ybc_set_txn_commit)*1 }; }
#line 37 "not-declared"
void __cgo_f_37_1(void) { __typeof__(ybc_set_txn_get_size) *__cgo_undefined__; }
#line 37 "not-type"
void __cgo_f_37_2(void) { ybc_set_txn_get_size *__cgo_undefined__; }
#line 37 "not-const"
void __cgo_f_37_3(void) { enum { __cgo__undefined__ = (ybc_set_txn_get_size)*1 }; }
#line 38 "not-declared"
void __cgo_f_38_1(void) { __typeof__(ybc_set_txn_get_value) *__cgo_undefined__; }
#line 38 "not-type"
void __cgo_f_38_2(void) { ybc_set_txn_get_value *__cgo_undefined__; }
#line 38 "not-const"
void __cgo_f_38_3(void) { enum { __cgo__undefined__ = (ybc_set_txn_get_value)*1 }; }
#line 39 "not-declared"
void __cgo_f_39_1(void) { __typeof__(ybc_set_txn_rollback) *__cgo_undefined__; }
#line 39 "not-type"
void __cgo_f_39_2(void) { ybc_set_txn_rollback *__cgo_undefined__; }
#line 39 "not-const"
void __cgo_f_39_3(void) { enum { __cgo__undefined__ = (ybc_set_txn_rollback)*1 }; }
#line 40 "not-declared"
void __cgo_f_40_1(void) { __typeof__(ybc_set_txn_update_value_size) *__cgo_undefined__; }
#line 40 "not-type"
void __cgo_f_40_2(void) { ybc_set_txn_update_value_size *__cgo_undefined__; }
#line 40 "not-const"
void __cgo_f_40_3(void) { enum { __cgo__undefined__ = (ybc_set_txn_update_value_size)*1 }; }
#line 41 "not-declared"
void __cgo_f_41_1(void) { __typeof__(ybc_simple_get) *__cgo_undefined__; }
#line 41 "not-type"
void __cgo_f_41_2(void) { ybc_simple_get *__cgo_undefined__; }
#line 41 "not-const"
void __cgo_f_41_3(void) { enum { __cgo__undefined__ = (ybc_simple_get)*1 }; }
#line 42 "not-declared"
void __cgo_f_42_1(void) { __typeof__(ybc_simple_set) *__cgo_undefined__; }
#line 42 "not-type"
void __cgo_f_42_2(void) { ybc_simple_set *__cgo_undefined__; }
#line 42 "not-const"
void __cgo_f_42_3(void) { enum { __cgo__undefined__ = (ybc_simple_set)*1 }; }
#line 1 "completed"
int __cgo__1 = __cgo__2;

full error output:
not-type:1:35: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_1_2(void) { CString *__cgo_undefined__; }
                                  ^
not-const:1:63: error: invalid operands to binary expression ('char *(*)(_GoString_)' and 'int')
void __cgo_f_1_3(void) { enum { __cgo__undefined__ = (CString)*1 }; }
                                                     ~~~~~~~~~^~
not-type:2:35: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_2_2(void) { GoBytes *__cgo_undefined__; }
                                  ^
not-const:2:63: error: invalid operands to binary expression ('_GoBytes_ (*)(void *, int)' and 'int')
void __cgo_f_2_3(void) { enum { __cgo__undefined__ = (GoBytes)*1 }; }
                                                     ~~~~~~~~~^~
not-type:3:43: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_3_2(void) { YBC_DE_NOTFOUND *__cgo_undefined__; }
                                          ^
not-type:4:42: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_4_2(void) { YBC_DE_SUCCESS *__cgo_undefined__; }
                                         ^
not-type:5:45: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_5_2(void) { YBC_DE_WOULDBLOCK *__cgo_undefined__; }
                                            ^
not-type:6:32: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_6_2(void) { free *__cgo_undefined__; }
                               ^
not-const:6:60: error: invalid operands to binary expression ('void (*)(void *)' and 'int')
void __cgo_f_6_3(void) { enum { __cgo__undefined__ = (free)*1 }; }
                                                     ~~~~~~^~
not-type:7:52: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_7_2(void) { go_commit_item_and_value *__cgo_undefined__; }
                                                   ^
not-const:7:80: error: invalid operands to binary expression ('void (*)(struct ybc_set_txn *const, struct ybc_item *const, struct ybc_value *const)' and 'int')
void __cgo_f_7_3(void) { enum { __cgo__undefined__ = (go_commit_item_and_value)*1 }; }
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
not-type:8:49: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_8_2(void) { go_get_item_and_value *__cgo_undefined__; }
                                                ^
not-const:8:77: error: invalid operands to binary expression ('int (*)(struct ybc *const, struct ybc_item *const, struct ybc_value *const, const struct ybc_key *const)' and 'int')
void __cgo_f_8_3(void) { enum { __cgo__undefined__ = (go_get_item_and_value)*1 }; }
                                                     ~~~~~~~~~~~~~~~~~~~~~~~^~
not-type:9:58: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_9_2(void) { go_get_item_and_value_de_async *__cgo_undefined__; }
                                                         ^
not-const:9:86: error: invalid operands to binary expression ('enum ybc_de_status (*)(struct ybc *const, struct ybc_item *const, struct ybc_value *const, const struct ybc_key *const, const uint64_t)' and 'int')
void __cgo_f_9_3(void) { enum { __cgo__undefined__ = (go_get_item_and_value_de_async)*1 }; }
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
not-type:10:50: error: use of undeclared identifier '__cgo_undefined__'
void __cgo_f_10_2(void) { go_set_item_and_value *__cgo_undefined__; }
                                                 ^
not-const:10:78: error: invalid operands to binary expression ('int (*)(struct ybc *const, struct ybc_item *const, const struct ybc_key *const, struct ybc_value *const)' and 'int')
void __cgo_f_10_3(void) { enum { __cgo__undefined__ = (go_set_item_and_value)*1 }; }
                                                      ~~~~~~~~~~~~~~~~~~~~~~~^~
not-const:11:60: error: indirection requires pointer operand ('int' invalid)
void __cgo_f_11_3(void) { enum { __cgo__undefined__ = (int)*1 }; }
                                                           ^~
not-const:12:63: error: indirection requires pointer operand ('int' invalid)
void __cgo_f_12_3(void) { enum { __cgo__undefined__ = (size_t)*1 }; }
                                                              ^~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by eapache** [comment] 2015-02-11 14:28
What makes you think this is a Sarama issue? Those errors don't look like they are in Sarama to me.

**Comment by eapache** [comment] 2015-02-12 03:57
Based on the question https://stackoverflow.com/questions/28454942/error-library-valyala-on-golang I am going to close this as not actually related to Sarama. Please feel free to open again if you find something indicating Sarama is the cause of the problem.

**Closed by eapache** 2015-02-12 03:57 UTC
Labels: needs-more-info
