### ISSUE TITLE
Producer hangs when `Retry.Max` is 0

### ISSUE THREAD

**Issue by eapache** [Shopify/sarama#294] opened 2015-02-23 20:10 UTC
(This is also poor behaviour in other configurations in that it can "waste" some of the configured retries, but is otherwise not a problem - it doesn't break ordering or anything.)

The `leaderDispatcher` function only knows to check for a new leader when it receives a message with a new retry value, but there are at least two cases (possibly more?) where for various reasons the `flusher` fails but never sends a retriable message to the leaderDispatcher:
- all of the messages are at their retry limit, and get returned to the user instead
- there is a topic/partition led by that broker, but with no messages in the current batch, when the broker connection dies

In both of the above cases, we can end up with a `leaderDispatcher` whose broker is toast, but doesn't know it and so doesn't try and get a new one.

In the normal case, the next message (not at the retry limit) will get spun around anyways and kick things off the way it should; this is less than ideal (we waste a retry for the message(s) in question) but not a very severe problem as by default we have three retries configured and typically only need one.

However, in the case where someone sets `MaxRetries` to 0, every subsequent message is immediately returned to the user and the producer ends up stuck.

**Comment by eapache** [comment] 2015-02-23 20:13
The following test will pass/fail this issue, it should be copied into `producer_test.go` when this is fixed.
```golang
func TestProducerOutOfRetries(t *testing.T) {
        seedBroker := NewMockBroker(t, 1)
        leader := NewMockBroker(t, 2)

        metadataResponse := new(MetadataResponse)
        metadataResponse.AddBroker(leader.Addr(), leader.BrokerID())
        metadataResponse.AddTopicPartition("my_topic", 0, leader.BrokerID(), nil, nil, NoError)
        seedBroker.Returns(metadataResponse)

        client, err := NewClient("client_id", []string{seedBroker.Addr()}, nil)
        if err != nil {
                t.Fatal(err)
        }

        config := NewProducerConfig()
        config.FlushMsgCount = 10
        config.AckSuccesses = true
        config.RetryBackoff = 0
        config.MaxRetries = 0
        producer, err := NewProducer(client, config)
        if err != nil {
                t.Fatal(err)
        }

        for i := 0; i < 10; i++ {
                producer.Input() <- &MessageToSend{Topic: "my_topic", Key: nil, Value: StringEncoder(TestMessage)}
        }

        prodNotLeader := new(ProduceResponse)
        prodNotLeader.AddTopicPartition("my_topic", 0, NotLeaderForPartition)
        leader.Returns(prodNotLeader)

        for i := 0; i < 10; i++ {
                select {
                case msg := <-producer.Errors():
                        if msg.Err != NotLeaderForPartition {
                                t.Error(msg.Err)
                        }
                case <-producer.Successes():
                        t.Error("Unexpected success")
                }
        }

        seedBroker.Returns(metadataResponse)

        for i := 0; i < 10; i++ {
                producer.Input() <- &MessageToSend{Topic: "my_topic", Key: nil, Value: StringEncoder(TestMessage)}
        }

        prodSuccess := new(ProduceResponse)
        prodSuccess.AddTopicPartition("my_topic", 0, NoError)
        leader.Returns(prodSuccess)

        for i := 0; i < 10; i++ {
                select {
                case msg := <-producer.Errors():
                        t.Error(msg.Err)
                case <-producer.Successes():
                }
        }

        leader.Close()
        seedBroker.Close()
        safeClose(t, producer)
        safeClose(t, client)
}
```

**Comment by wvanbergen** [comment] 2015-02-25 20:22
I feel the solution should be that we have a way to actively invalidate (remove) metadata as soon as we encounter a problem, so the subsequent message has no choice but to request fresh metadata. Maybe we should invalidate all cached metadata for a broker in `disconnectBroker`?

**Comment by eapache** [comment] 2015-02-25 20:27
The problem is not actually in the client - the metadata in the client is correctly invalidated in this case. The problem is that the `leaderDispatcher` keeps a local "cache" of its `brokerProducer` (via the local `output` variable), and it relies on a "retried" message to come back in order to invalidate that cache.

**Comment by eapache** [comment] 2015-02-25 20:37
Once #300 happens there are several easy ways to solve this. One of them is to fetch the `brokerProducer` on every iteration of the `leaderDispatcher` (which would require tweaking how we reference-count those slightly). Another is to send a dummy "trigger" message (using flags) around on failure to all the affected `leadersDispatchers`, even if they didn't have a message in the batch.

**Comment by wkuranowski** [comment] 2015-08-13 14:14
Hello. So it looks like my issue #509 is a duplicate of this bug. Do you have any plan to fix that issue?

Now I am trying to configure built-in retry mechanism, but I have a question. Are you retrying network and circuit breaker errors? I am using a round robin partitioner and it will be great if you can automatically reassign partition in case of circuit breaker or network error.

**Comment by eapache** [comment] 2015-08-13 14:19
> Do you have any plan to fix that issue?

Yes, it's just slow going as it mostly depends on the refactoring in #300. That is almost done however.

> Are you retrying network and circuit breaker errors?

The producer retries only errors resulting from actual Produce requests. Errors from metadata requests and similar are not retried in the producer because they are already retried at the client level. Errors from circuit-breakers are not retried, because that would defeat the entire purpose of having the circuit-breaker.

**Comment by wkuranowski** [comment] 2015-08-13 14:38
> Errors from metadata requests and similar are not retried in the producer because they are already retried at the client level. 

And what about network errors when producing a message? Is this the same case?

> Errors from circuit-breakers are not retried, because that would defeat the entire purpose of having the circuit-breaker.

You can automatically assign an available partition when using random or round robin partitioner. Ordering is not important for that messages.

**Comment by eapache** [comment] 2015-08-13 14:53
> And what about network errors when producing a message?

Network errors when producing a message are retried.

> You can automatically assign an available partition when using random or round robin partitioner. Ordering is not important for that messages.

Hmm, yes that would be a good improvement. Perhaps file a separate enhancement request to track this idea.

**Comment by varun06** [comment] 2019-02-20 15:14
Does anyone know if this is still an issue. Can we close it now? @bai @eapache

**Comment by bai** [comment] 2019-02-20 15:26
Hmmm, doesn't seem so — I'm going to close it but feel free to reopen if you think otherwise 🙌

**Closed by bai** 2019-02-20 15:26 UTC
Labels: bug, producer
