### ISSUE TITLE
Need support kerberos plaintext auth.

### ISSUE THREAD

**Issue by yzpnet** [Shopify/sarama#1429] opened 2019-07-18 09:29 UTC
##### Versions

Sarama Version:v1.23.0
Kafka Version:0.9.0.1
Go Version:1.12

##### Configuration

```
cfg.Net.SASL.Mechanism = sarama.SASLTypeGSSAPI
cfg.Net.SASL.Enable = true
cfg.Net.SASL.GSSAPI.ServiceName = "kafka"
cfg.Net.SASL.GSSAPI.Realm = global.Config.Kafka.Principal
cfg.Net.SASL.GSSAPI.Username = "client"
cfg.Net.SASL.GSSAPI.AuthType = sarama.KRB5_KEYTAB_AUTH
cfg.Net.SASL.GSSAPI.KeyTabPath = global.Config.Kafka.KeyTabPath
cfg.Net.SASL.GSSAPI.KerberosConfigPath = "/etc/krb5.conf"
```

##### Logs

kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

##### Problem Description

Need support kerberos plaintext auth.

**Comment by rubenvp8510** [comment] 2019-08-15 19:59
This is actually supported and is the only method for authenticated with kerberos (PLAIN_TEXT) I think you are facing another error related to the encryption, 

See my comments on the original PR, if the outlined steps there works for you we can close this.

**Comment by d1egoaz** [comment] 2019-08-22 16:05
@yzpnet please let us know if you could sorted this out.

**Comment by yzpnet** [comment] 2019-08-23 11:53
My krb5.conf:
```
[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 default_realm = DEMO.COM
 dns_lookup_realm = false
 dns_lookup_kdc = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 rdns = false
 master_key_type = des3-hmac-sha1
 default_tgs_enctypes = des3-hmac-sha1 des-cbc-crc des-cbc-md5
 default_tkt_enctypes = des3-hmac-sha1 des-cbc-crc des-cbc-md5
 permitted_enctypes = des3-hmac-sha1 des-cbc-crc des-cbc-md5


[realms]

DEMO.COM = {
  kdc = node1.test.gmq.demo.com:88
  kdc = node2.test.gmq.demo.com:88
  admin_server = node1.test.gmq.demo.com:749
  supported_enctypes = des3-hmac-sha1:normal des-cbc-crc:normal
  master_key_type = des3-hmac-sha1
 }

[domain_realm]
 .demo.com = DEMO.COM
 demo.com = DEMO.COM

[appdefaults]
 pam= {
  debug = false
  ticket_lifetime = 36000
  renew_lifetime = 36000
  forwardable = true
  krb4_convert = false
 }
```

**When I do not set DisablePAFXFAST = true.**

```
client = krb5client.NewClientWithKeytab(config.Username, config.Realm, kt, cfg)
```

**There are some errors.**

```
2019/08/23 19:27:13 Starting a new Sarama consumer
[sarama] 2019/08/23 19:27:13 Initializing new client
[sarama] 2019/08/23 19:27:13 client/metadata fetching metadata for all topics from broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:13 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:27:13 Closed connection to broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:13 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:27:13 client/metadata fetching metadata for all topics from broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:13 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:27:13 Closed connection to broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:13 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:27:13 client/metadata no available broker to send metadata request to
[sarama] 2019/08/23 19:27:13 client/brokers resurrecting 2 dead seed brokers
[sarama] 2019/08/23 19:27:13 client/metadata retrying after 250ms... (3 attempts remaining)
[sarama] 2019/08/23 19:27:14 client/metadata fetching metadata for all topics from broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:14 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:27:14 Closed connection to broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:14 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:27:14 client/metadata fetching metadata for all topics from broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:14 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:27:14 Closed connection to broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:14 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:27:14 client/metadata no available broker to send metadata request to
[sarama] 2019/08/23 19:27:14 client/brokers resurrecting 2 dead seed brokers
[sarama] 2019/08/23 19:27:14 client/metadata retrying after 250ms... (2 attempts remaining)
[sarama] 2019/08/23 19:27:14 client/metadata fetching metadata for all topics from broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:14 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:27:14 Closed connection to broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:14 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:27:14 client/metadata fetching metadata for all topics from broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:14 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:27:14 Closed connection to broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:14 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:27:14 client/metadata no available broker to send metadata request to
[sarama] 2019/08/23 19:27:14 client/brokers resurrecting 2 dead seed brokers
[sarama] 2019/08/23 19:27:14 client/metadata retrying after 250ms... (1 attempts remaining)
[sarama] 2019/08/23 19:27:14 client/metadata fetching metadata for all topics from broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:14 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:27:14 Closed connection to broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:14 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:27:14 client/metadata fetching metadata for all topics from broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:14 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:27:14 Closed connection to broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:27:14 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:27:14 client/metadata no available broker to send metadata request to
[sarama] 2019/08/23 19:27:14 client/brokers resurrecting 2 dead seed brokers
[sarama] 2019/08/23 19:27:14 Closing Client
2019/08/23 19:27:14 Error creating consumer group client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
panic: Error creating consumer group client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

**When I set DisablePAFXFAST = true(Directly modifying the vendor code).**

```
client = krb5client.NewClientWithKeytab(config.Username, config.Realm, kt, cfg, krb5client.DisablePAFXFAST(true))
```

**There are still some errors.**

```
2019/08/23 19:38:40 Starting a new Sarama consumer
[sarama] 2019/08/23 19:38:40 Initializing new client
[sarama] 2019/08/23 19:38:40 client/metadata fetching metadata for all topics from broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:40 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:38:40 Closed connection to broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:40 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:38:40 client/metadata fetching metadata for all topics from broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:40 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:38:40 Closed connection to broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:40 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:38:40 client/metadata no available broker to send metadata request to
[sarama] 2019/08/23 19:38:40 client/brokers resurrecting 2 dead seed brokers
[sarama] 2019/08/23 19:38:40 client/metadata retrying after 250ms... (3 attempts remaining)
[sarama] 2019/08/23 19:38:41 client/metadata fetching metadata for all topics from broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:41 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:38:41 Closed connection to broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:41 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:38:41 client/metadata fetching metadata for all topics from broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:41 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:38:41 Closed connection to broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:41 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND
[sarama] 2019/08/23 19:38:41 client/metadata no available broker to send metadata request to
[sarama] 2019/08/23 19:38:41 client/brokers resurrecting 2 dead seed brokers
[sarama] 2019/08/23 19:38:41 client/metadata retrying after 250ms... (2 attempts remaining)
[sarama] 2019/08/23 19:38:41 client/metadata fetching metadata for all topics from broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:41 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:38:41 Closed connection to broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:41 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:38:41 client/metadata fetching metadata for all topics from broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:41 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:38:41 Closed connection to broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:41 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:38:41 client/metadata no available broker to send metadata request to
[sarama] 2019/08/23 19:38:41 client/brokers resurrecting 2 dead seed brokers
[sarama] 2019/08/23 19:38:41 client/metadata retrying after 250ms... (1 attempts remaining)
[sarama] 2019/08/23 19:38:41 client/metadata fetching metadata for all topics from broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:41 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:38:41 Closed connection to broker dispatch.node2.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:41 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:38:41 client/metadata fetching metadata for all topics from broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:41 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:38:41 Closed connection to broker dispatch.node1.test.gmq.demo.com:9094
[sarama] 2019/08/23 19:38:41 client/metadata got error from broker -1 while fetching metadata: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE
[sarama] 2019/08/23 19:38:41 client/metadata no available broker to send metadata request to
[sarama] 2019/08/23 19:38:41 client/brokers resurrecting 2 dead seed brokers
[sarama] 2019/08/23 19:38:41 Closing Client
2019/08/23 19:38:41 Error creating consumer group client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
panic: Error creating consumer group client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

**My test code is:**

```
package main

import (
	"context"
	"flag"
	"gopkg.in/Shopify/sarama.v1"
	"log"
	"os"
	"os/signal"
	"strings"
	"sync"
	"syscall"
)

// Sarma configuration options
var (
	brokers = ""
	version = ""
	group   = ""
	topics  = ""
	oldest  = true
	verbose = false
)

func init() {
	flag.StringVar(&brokers, "brokers", "", "Kafka bootstrap brokers to connect to, as a comma separated list")
	flag.StringVar(&group, "group", "", "Kafka consumer group definition")
	flag.StringVar(&version, "version", "1.1.1", "Kafka cluster version")
	flag.StringVar(&topics, "topics", "", "Kafka topics to be consumed, as a comma seperated list")
	flag.BoolVar(&oldest, "oldest", true, "Kafka consumer consume initial ofset from oldest")
	flag.BoolVar(&verbose, "verbose", false, "Sarama logging")
	flag.Parse()

	if len(brokers) == 0 {
		panic("no Kafka bootstrap brokers defined, please set the -brokers flag")
	}

	if len(topics) == 0 {
		panic("no topics given to be consumed, please set the -topics flag")
	}

	if len(group) == 0 {
		panic("no Kafka consumer group defined, please set the -group flag")
	}
}

func main() {
	log.Println("Starting a new Sarama consumer")

	if verbose {
		sarama.Logger = log.New(os.Stdout, "[sarama] ", log.LstdFlags)
	}

	version, err := sarama.ParseKafkaVersion(version)
	if err != nil {
		log.Panicf("Error parsing Kafka version: %v", err)
	}

	/**
	 * Construct a new Sarama configuration.
	 * The Kafka cluster version has to be defined before the consumer/producer is initialized.
	 */
	kafkaConfig := sarama.NewConfig()
	kafkaConfig.Version = version
	kafkaConfig.ClientID = "kafka"

	kafkaConfig.Net.SASL.Mechanism = sarama.SASLTypeGSSAPI
	kafkaConfig.Net.SASL.Enable = true
	kafkaConfig.Net.SASL.GSSAPI.ServiceName = "kafka"
	kafkaConfig.Net.SASL.GSSAPI.Realm = "DEMO.COM"
	kafkaConfig.Net.SASL.GSSAPI.Username = "kafka-user"
	kafkaConfig.Net.SASL.GSSAPI.AuthType = sarama.KRB5_KEYTAB_AUTH
	kafkaConfig.Net.SASL.GSSAPI.KeyTabPath = "./kafka-user@DEMO.COM.keytab"
	kafkaConfig.Net.SASL.GSSAPI.KerberosConfigPath = "./krb5.conf"

	if oldest {
		kafkaConfig.Consumer.Offsets.Initial = sarama.OffsetOldest
	}

	/**
	 * Setup a new Sarama consumer group
	 */
	consumer := Consumer{
		ready: make(chan bool),
	}

	ctx, cancel := context.WithCancel(context.Background())
	client, err := sarama.NewConsumerGroup(strings.Split(brokers, ","), group, kafkaConfig)
	if err != nil {
		log.Panicf("Error creating consumer group client: %v", err)
	}

	wg := &sync.WaitGroup{}
	wg.Add(1)
	go func() {
		defer wg.Done()
		for {
			if err := client.Consume(ctx, strings.Split(topics, ","), &consumer); err != nil {
				log.Panicf("Error from consumer: %v", err)
			}
			// check if context was cancelled, signaling that the consumer should stop
			if ctx.Err() != nil {
				return
			}
			consumer.ready = make(chan bool)
		}
	}()

	<-consumer.ready // Await till the consumer has been set up
	log.Println("Sarama consumer up and running!...")

	sigterm := make(chan os.Signal, 1)
	signal.Notify(sigterm, syscall.SIGINT, syscall.SIGTERM)
	select {
	case <-ctx.Done():
		log.Println("terminating: context cancelled")
	case <-sigterm:
		log.Println("terminating: via signal")
	}
	cancel()
	wg.Wait()
	if err = client.Close(); err != nil {
		log.Panicf("Error closing client: %v", err)
	}
}

// Consumer represents a Sarama consumer group consumer
type Consumer struct {
	ready chan bool
}

// Setup is run at the beginning of a new session, before ConsumeClaim
func (consumer *Consumer) Setup(sarama.ConsumerGroupSession) error {
	// Mark the consumer as ready
	close(consumer.ready)
	return nil
}

// Cleanup is run at the end of a session, once all ConsumeClaim goroutines have exited
func (consumer *Consumer) Cleanup(sarama.ConsumerGroupSession) error {
	return nil
}

// ConsumeClaim must start a consumer loop of ConsumerGroupClaim's Messages().
func (consumer *Consumer) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {

	// NOTE:
	// Do not move the code below to a goroutine.
	// The `ConsumeClaim` itself is called within a goroutine, see:
	// https://github.com/Shopify/sarama/blob/master/consumer_group.go#L27-L29
	for message := range claim.Messages() {
		log.Printf("Message claimed: value = %s, timestamp = %v, topic = %s", string(message.Value), message.Timestamp, message.Topic)
		session.MarkMessage(message, "")
	}

	return nil
}
```

**Running script:**

```
go run main.go -brokers="dispatch.node1.test.gmq.demo.com:9094,dispatch.node2.test.gmq.demo.com:9094" -topics="test_topic" -group="test_group" -verbose=true
```

**It’s working well on confluent(dependent on librdkafka).**

**But I do not want to use confluent, because it dependent on c code.**

```
client.topics = topics
client.groupId = groupId
configMap := &kafka.ConfigMap{
	"bootstrap.servers":       global.Config.Kafka.Brokers,
	"group.id":                groupId,
	"api.version.request":     false,
	"broker.version.fallback": common.KafkaVersion,
	"broker.address.family":   "v4",
	"max.poll.interval.ms":    300000,
	"session.timeout.ms":      6000,
	"auto.offset.reset":       AutoOffsetResetLatest,
}
if global.Config.Kafka.AuthSwitch {
	(*configMap)["security.protocol"] = "sasl_plaintext"
	(*configMap)["sasl.kerberos.service.name"] = "kafka"
	(*configMap)["sasl.kerberos.principal"] = global.Config.Kafka.Principal
	(*configMap)["sasl.kerberos.keytab"] = global.Config.Kafka.KeyTabPath
	(*configMap)["sasl.kerberos.kinit.cmd"] = "kinit -r 5d -k -t \"%{sasl.kerberos.keytab}\" %{sasl.kerberos.principal}"
}
consumer, err := kafka.NewConsumer(configMap)
```

**It’s also working well on php(dependent on php-ext rdkafka)**

**Comment by yzpnet** [comment] 2019-08-23 11:55
@d1egoaz @rubenvp8510 Please help me see the problem.

**Comment by rubenvp8510** [comment] 2019-08-23 12:39
It seems like the KDC cannot found the principal

`[sarama] 2019/08/23 19:38:40 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND`

This is a direct error returned by the KDC

Does kinit command works for that principal?

` kinit -k -t ./kafka-user@DEMO.COM.keytab kafka-user@DEMO.COM ?`

**Comment by rubenvp8510** [comment] 2019-08-23 12:58
Are you using Active Directory? or MIT Kerberos?

**Comment by yzpnet** [comment] 2019-08-26 02:51
> ` kinit -k -t ./kafka-user@DEMO.COM.keytab kafka-user@DEMO.COM ?`

The keytab file is in the current directory.
The krb5.conf is in the etc directory.

It works.

**Comment by yzpnet** [comment] 2019-08-26 02:55
My system is Mac OS X.
```
protocol :sasl_plaintext
cmd:kinit -k -t ./kafka-user@DEMO.COM.keytab kafka-user@DEMO.COM
lib:librdkafka 1.1.0
```

**Comment by yzpnet** [comment] 2019-08-26 02:58
MIT Kerberos.

**Comment by yzpnet** [comment] 2019-08-30 09:19
@rubenvp8510 Please help me solve it.

**Comment by rubenvp8510** [comment] 2019-08-30 20:35
Hi @yzpnet could you provide me with your server set-up? I want to try to replicate the scenario so I can figure out what is happening.

**Comment by yzpnet** [comment] 2019-09-04 03:32
@rubenvp8510 Thanks a lot.

My kafka server version is **0.9.0.1**.

**Server config**:

```
broker.id=1
listeners=PLAINTEXT://172.16.1.100:9092,SASL_PLAINTEXT://node1.test.gmq.demo.com:9094
security.inter.broker.protocol=SASL_PLAINTEXT
host.name=node1.test.gmq.demo.com
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
log.dirs=/data/kafka-logs/
num.partitions=4
num.recovery.threads.per.data.dir=1
log.retention.hours=24
message.max.byte=5242880
default.replication.factor=2
replica.fetch.max.bytes=5242880
log.segment.bytes=536870912
log.roll.hours=12
log.retention.check.interval.ms=300000
zookeeper.connect=a.b.c.d:2181,e.f.g.h:2181,i.j.k.l:2181
zookeeper.connection.timeout.ms=20000
delete.topic.enable=true
authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer
allow.everyone.if.no.acl.found=true
sasl.kerberos.service.name=kafka
security.inter.broker.protocol=SASL_PLAINTEXT
sasl.mechanism.inter.broker.protocol=GSSAPI
sasl.enabled.mechanisms=GSSAPI
super.users=User:kafka
log.cleaner.dedupe.buffer.size=805306368
```

**Comment by rubenvp8510** [comment] 2019-09-04 05:00
@yzpnet  if you could also attach your kerberos server configuration that would be very useful, because the error you are seeing is not a kafka error but a KDC error, related to the communication between the client and the kerberos server.

**Comment by yzpnet** [comment] 2019-09-04 06:07
@rubenvp8510 

**Kerberos kdc config is**

```
[kdcdefaults]
 kdc_ports = 88
 kdc_tcp_ports = 88

[realms]
 DEMO.COM = {
  #master_key_type = aes256-cts
  acl_file = /var/kerberos/krb5kdc/kadm5.acl
  dict_file = /usr/share/dict/words
  admin_keytab = /var/kerberos/krb5kdc/kadm5.keytab
  supported_enctypes = aes256-cts:normal aes128-cts:normal des3-hmac-sha1:normal arcfour-hmac:normal des-hmac-sha1:normal des-cbc-md5:normal des-cbc-crc:normal
 }
```

**Comment by yzpnet** [comment] 2019-09-24 03:53
@rubenvp8510 
Did you solve this problem?

**Comment by yzpnet** [comment] 2019-10-15 09:44
@rubenvp8510 Solved?

**Comment by rubenvp8510** [comment] 2019-10-15 15:30
Hi, sorry I haven't had a chance to review this in detail, I'll try to reproduce today and post my results or submit a new PR if it's required.

**Comment by yzpnet** [comment] 2019-10-16 04:00
Many thanks!
Looking forward to your results.

**Comment by rubenvp8510** [comment] 2019-10-16 22:32
Hi, reporting my results:

I tried to reproduce this issue, but wasn't able to fully reproduce it. First of all, I see two main errors in your logs:

One is this:

`[sarama] 2019/08/23 19:38:40 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database - CLIENT_NOT_FOUND`

But the other is this one (note that this is from a diferent KDC server):

`[sarama] 2019/08/23 19:38:41 Kerberos client error: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE`


Note that you have two different KDC servers associated with one realm.


I used your posted `krb5.conf` file from https://github.com/Shopify/sarama/issues/1429#issuecomment-524286938 and was able to reproduce the `BAD_ENCRYPTION_TYPE`. But not the `CLIENT_NOT_FOUND`

now, this is my theory:

In one of your KDC the user does not exists , the other one is where the user exists but is throwing the BAD_ENCRYPTION_TYPE error.

If I commented  the following lines from the krb5.conf (client side)

```
#    default_tgs_enctypes = des3-hmac-sha1 des-cbc-crc des-cbc-md5
#    default_tkt_enctypes = des3-hmac-sha1 des-cbc-crc des-cbc-md5
```

then  I was able to authenticate with KDC, still not sure the root cause or if this is de correct behavior, I'm investigating, In any case, this seems to  be an issue with the library I'm using for Kerberos communication  (with KDC), I'll raise a ticket into the library repository.

Could you please try to comment those lines and test if that works for you?

This is my final krb5.conf file:

```
includedir /etc/krb5.conf.d/

[logging]
    default = FILE:/var/log/krb5libs.log
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmind.log

[libdefaults]
    dns_lookup_realm = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    dns_lookup_kdc = false
    rdns = false
    pkinit_anchors = /etc/pki/tls/certs/ca-bundle.crt
    spake_preauth_groups = edwards25519
    default_realm = EXAMPLE.COM
    master_key_type = des3-hmac-sha1
#    default_tgs_enctypes = des3-hmac-sha1 des-cbc-crc des-cbc-md5
#    default_tkt_enctypes = des3-hmac-sha1 des-cbc-crc des-cbc-md5
    permitted_enctypes = des3-hmac-sha1 des-cbc-crc des-cbc-md5


[realms]
EXAMPLE.COM = {
#     supported_enctypes = des3-hmac-sha1:normal des-cbc-crc:normal
     master_key_type = des3-hmac-sha1
     kdc = kerberos.example.com
     admin_server = kerberos.example.com
}

[domain_realm]
 .example.com = EXAMPLE.COM
  example.com = EXAMPLE.COM
```

I used EXAMPLE.COM as a realm, you can change it to yours.

Thanks

**Comment by rubenvp8510** [comment] 2019-10-16 23:55
Ok I found one explanation, is not an issue on the gokrb5 library, but the only supported encryption types are: https://github.com/jcmturner/gokrb5#implemented-encryption--checksum-types

And no one of the default enctypes that you specified are listed there.

May be in the future they decided to  add more, not sure, but meanwhile we don't have another options. (as far as I know). :(

**Comment by yzpnet** [comment] 2019-10-21 02:03
Thanks a lot!

**Closed** 2019-10-21 02:03 UTC
Labels: Waiting for response

**Comment by rubenvp8510** [comment] 2019-10-21 03:28
@yzpnet this worked for you?
