### ISSUE TITLE
Not all messages are being flushed out of Kafka.

### ISSUE THREAD

**Issue by twanies** [Shopify/sarama#637] opened 2016-04-04 12:58 UTC
We encountered the following issue:

If we produce 10 messages to Kafka we only consume 9. The last message is never consumed till a new message is produced.

Replicating this problem is straight forward:

Produce **n** number of messaged to Kafka and let a consumer consume them all. You will see that the consumer only consumes **n - 1**.

Is this a bug in the lib? Or are we missing a configuration setting?

Cheers A.

**Comment by wvanbergen** [comment] 2016-04-04 13:10
The test suite makes sure this is working properly. I assume you are missing something in your setup.

One thing: if you ask for the latest offset for a partition, you will actually get the offset of the next message that will be produced, instead of the offset of the message that was produced last. This could explain your off by one error.

**Comment by wvanbergen** [comment] 2016-04-09 11:33
Going to close this because I am pretty sure this is not a bug. You can check out the test suite, which tests exactly for this scenario. Feel free to re-open this with a code snippet and ideally the output of `sarama.Logger` if you still think something is broken.

**Closed by wvanbergen** 2016-04-09 11:33 UTC
