### ISSUE TITLE
Manually commit offset not working

### ISSUE THREAD

**Issue by vikrampunchh** [Shopify/sarama#1662] opened 2020-04-09 11:59 UTC
My code is:

```
config.Consumer.Offsets.AutoCommit.Enable = false
```

```
func (consumer *Consumer) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
	for message := range claim.Messages() {
		log.Printf("Message claimed: value = %s, timestamp = %v, topic = %s, offset = %d", string(message.Value), message.Timestamp, message.Topic, message.Offset)
		session.MarkMessage(message, "")
	}

	return nil
}
```

after restart consumer, consumer receive all old offset that are `MarkMessage`.

**Comment by cheesedosa** [comment] 2020-04-11 22:04
What is the value of `config.Consumer.Offsets.AutoCommit.Interval`?

When autocommit is disabled, offsets will be flushed at the above interval. Default is `1s`.

**Comment by vikrampunchh** [comment] 2020-04-13 06:17
I am using Default `1s`. but receiving message every time when restart consumer.

**Comment by vikrampunchh** [comment] 2020-04-14 09:38
I try to trace code:

```
// flushToBroker is ignored if auto-commit offsets is disabled
func (om *offsetManager) flushToBroker() {
	if !om.conf.Consumer.Offsets.AutoCommit.Enable {
		return
	}
// ....

}
```

if we disable AutoCommit then it will never `flushToBroker`.

**Comment by dnwe** [comment] 2020-04-15 00:33
Yep this is a known flaw ref https://github.com/Shopify/sarama/issues/1570#issuecomment-574908417

**Comment by crazytaxi824** [comment] 2020-05-05 06:26
ok, this explains my confusion.

**Comment by dnwe** [comment] 2020-06-24 05:11
Closing as dupe of #1570

**Closed by dnwe** 2020-06-24 05:11 UTC
