### ISSUE TITLE
Issues with Producer.Retry.Max = 0

### ISSUE THREAD

**Issue by wkuranowski** [Shopify/sarama#509] opened 2015-08-13 09:21 UTC
Hello.

I am testing sarama 1.4.3 and have some issues with disabled retries. I disable them because I just want to retry only important stuff by myself.

I use AsyncProducer, 5 brokers and topic with replication factor = 2 and 10 partitions.

Everything works good until I shut down any broker (controlled.shutdown.enable=true). Kafka elects new leaders for partitions, but sarama doesn't see that and has permanent problem to produce to partitions with a new leader.

On errors channel I see `write tcp 127.0.0.1:9096: broken pipe` for every message produced to that partitions (round robin partitioner).

In logs I see only those lines:
>[Sarama] 2015/08/12 18:42:58 producer/flusher/5 state change to [closing] because write tcp 127.0.0.1:9096: broken pipe
>[Sarama] 2015/08/12 18:42:58 Closed connection to broker localhost:9096

I left my workstation for a night and today I started to produce new messages (1 broker still off, 4 available). This time sarama has problem to produce to any partition in a cluster. I see `broken pipe` for every message. Restart of my sarama based application was the only solution...

**Comment by eapache** [comment] 2015-08-13 11:59
Duplicate of #294.

**Closed by eapache** 2015-08-13 11:59 UTC
