### ISSUE TITLE
panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by liuxp0827** [Shopify/sarama#909] opened 2017-07-03 07:51 UTC
panic: sync: negative WaitGroup counter

goroutine 102 [running]:
sync.(*WaitGroup).Add(0xc42025a200, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:75 +0x1c9
sync.(*WaitGroup).Done(0xc42025a200)
	/usr/local/go/src/sync/waitgroup.go:100 +0x34
github.com/Shopify/sarama.(*asyncProducer).returnSuccesses(0xc42025a1c0, 0xc420252070, 0x1, 0x1)
	/usr/local/golang/src/github.com/Shopify/sarama/async_producer.go:848 +0x65
github.com/Shopify/sarama.(*brokerProducer).handleSuccess.func1(0xc4201f02f0, 0x10, 0xc400000000, 0xc420252070, 0x1, 0x1)
	/usr/local/golang/src/github.com/Shopify/sarama/async_producer.go:739 +0x159
github.com/Shopify/sarama.(*produceSet).eachPartition(0xc42062c960, 0xc4205d5d70)
	/usr/local/golang/src/github.com/Shopify/sarama/produce_set.go:118 +0x13f
github.com/Shopify/sarama.(*brokerProducer).handleSuccess(0xc4202b36e0, 0xc42062c960, 0xc42062ca80)
	/usr/local/golang/src/github.com/Shopify/sarama/async_producer.go:752 +0x5e
github.com/Shopify/sarama.(*brokerProducer).handleResponse(0xc4202b36e0, 0xc42062cac0)
	/usr/local/golang/src/github.com/Shopify/sarama/async_producer.go:704 +0x1cc
github.com/Shopify/sarama.(*brokerProducer).run(0xc4202b36e0)
	/usr/local/golang/src/github.com/Shopify/sarama/async_producer.go:638 +0xbbb
github.com/Shopify/sarama.(*brokerProducer).(github.com/Shopify/sarama.run)-fm()
	/usr/local/golang/src/github.com/Shopify/sarama/async_producer.go:537 +0x2a
github.com/Shopify/sarama.withRecover(0xc4206de290)
	/usr/local/golang/src/github.com/Shopify/sarama/utils.go:46 +0x43
created by github.com/Shopify/sarama.(*asyncProducer).newBrokerProducer
	/usr/local/golang/src/github.com/Shopify/sarama/async_producer.go:537 +0x29b

**Comment by eapache** [comment] 2017-07-04 13:30
What version of Sarama are you running? Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly. In particular, if you're using an older version this may be a duplicate of #449.

What configuration values are you using for your producer?

**Closed** 2017-07-27 20:36 UTC

**Comment by Dufresh** [comment] 2017-08-01 06:36
I also get this panic:
