### ISSUE TITLE
GetMemberMetadata, kafka: error decoding packet: invalid length

### ISSUE THREAD

**Issue by brzyangg** [Shopify/sarama#1801] opened 2020-09-17 07:37 UTC
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.27.0  | v2.2.1  | v1.14.0  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
        config.Version = sarama.V2_0_0_0
	config.Metadata.RefreshFrequency = 5 * time.Minute
	config.Net.KeepAlive = 15 * time.Minute
	config.Net.MaxOpenRequests = 102
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
kafka: error decoding packet: invalid length
```

</p>
</details>

##### Problem Description

first, i am use broker.DescribeGroups() get all groups, and range group.members, GetMemberMetadata, final some GetMemberMetadata return err

**Comment by dnwe** [comment] 2020-09-17 07:49
@brzyangg i think this is a dupe of https://github.com/Shopify/sarama/issues/1717 and was a server-side broker issue rather than a client problem

**Comment by dnwe** [comment] 2020-09-17 07:51
Note also that the Kafka Java adminclient only deserializes the member assignments, *not* the member metadata.
https://github.com/apache/kafka/blob/1d24e2e3b2a119997fc6805f9c754a5ee286d7b2/clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java#L2960-L2964 so you probably don’t really want to either

**Comment by brzyangg** [comment] 2020-09-17 07:59
thank you

**Closed** 2020-09-17 08:18 UTC
