### ISSUE TITLE
Lack of documentation and configuration for AsyncProducer circuit breaker

### ISSUE THREAD

**Issue by mkevac** [Shopify/sarama#961] opened 2017-10-05 12:45 UTC
Hi.

Seems that sarama lacks documentation for AsyncProducer circuit breaker. There is none.
Also, circuit breaker configuration (errorThreshold, successThreshold, timeout) is not available from outside and their values are hardcoded in async_producer.go.

Additionally, there is no good way for a user of sarama to understand that circuit breaker is open for him to be able to do something about that. In the usual case when someone is sending hundreds of thousands of messages per second and prints all the errors, he will get hundreds of thousands of errors printed. 

I think that this needs fixing or at least mentioning in docs.

Version: last master (61d6997607d1fa1f0d565dac179053597e8e7a64)

**Comment by eapache** [comment] 2017-10-05 14:10
You are probably right that this could be improved, but I would note the reasons that I did not originally document it or make it configurable:
- The circuit-breaker configuration was intentionally fairly conservative; the only adjustment I can think that users might want to do is to make it more aggressive, not less?
- Its placement into the producer was intended to be fairly transparent: it should only cause messages to fail if they would have failed anyway for a "real" reason. It makes the failure more efficient but shouldn't fundamentally affect behaviour.

I am not opposed to exposing some documentation or configuration, but given the above I am curious what case you are running into where the circuit breaker is causing problems? If you are sending hundreds of thousands of messages (and thus getting hundreds of thousands of errors), then it seems likely that something has gone wrong with your kafka connection and you would be getting those errors with or without a breaker in the middle?

**Comment by mkevac** [comment] 2017-10-05 15:32
Suppose I am producing 100000 msg/sec. And suppose my Kafka cluster is down. In a case when there is no circuit breaker I would get N errors per sec where N = 1 second / timeout. This is 1 message per second for 1 second timeout. Perfectly normal to write these errors to log file for example.
With circuit breaker, I am getting 100000 errors/sec. Because timeout is virtually non-existent in this case. I am getting the error right away. 100000 errors/sec is too excessive I think.

Additionally, as I have already mentioned, I don't know whether these errors are from the circuit breaker or not. This particular error is being sent straight from circuit breaker package that you use. Without any wrapping. So sarama does not have this error exported, it is not part of saramas API and I cannot use equality to understand which error it is.
If I could, I could add 1s timeout for example.

**Comment by eapache** [comment] 2017-10-05 16:18
> Suppose I am producing 100000 msg/sec. And suppose my Kafka cluster is down. In a case when there is no circuit breaker I would get N errors per sec where N = 1 second / timeout.

And then you run out of memory, because 10 seconds later you have a million messages queued up with nowhere to go?

If you're handling that volume of messages and the cluster is down, aren't you basically forced to drop those messages anyway? And doesn't that count as an error? Or do you have some sort of internal disk queueing you can use to hold them in the meantime?

> This particular error is being sent straight from circuit breaker package that you use. Without any wrapping. So sarama does not have this error exported, it is not part of saramas API and I cannot use equality to understand which error it is.

Hmm, yes this is a problem. The error *is* exported from the breaker package, so you can absolutely just import that package and then check against `breaker.ErrBreakerOpen` but that should definitely be documented.

**Comment by mkevac** [comment] 2017-10-08 18:18
> And then you run out of memory, because 10 seconds later you have a million messages queued up with nowhere to go? If you're handling that volume of messages and the cluster is down, aren't you basically forced to drop those messages anyway? And doesn't that count as an error? Or do you have some sort of internal disk queueing you can use to hold them in the meantime?

It is a contrived example. So you may be right.
But I don't see the need for circuit breaker here. At least it should be configurable or there should be a way to turn it off.

**Comment by eapache** [comment] 2017-10-10 15:01
> But I don't see the need for circuit breaker here.

The circuit-breaker is needed for situations where a significant part, but not all, of the cluster goes down (e.g. 6 of 12 brokers, or something like that). In that case there will be partitions with no active leaders; without a circuit breaker the entire producer would slow to a crawl while trying to process each message. The circuit-breaker opens to keep the messages flowing, allowing messages to the remaining online partitions to be produced.

> It is a contrived example.

Kafka is a dangerous system for contrived examples because of some design subtleties. If you have a real use case please feel free to open a new ticket.

**Closed by eapache** 2017-10-10 15:01 UTC
