### ISSUE TITLE
partitionOffsetManager will skip intermediate offsets if I don't mark offsets in order

### ISSUE THREAD

**Issue by xianglinghui** [Shopify/sarama#1287] opened 2019-02-20 13:04 UTC
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:
Kafka Version:
Go Version:

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

Hi，I found that partitionOffsetManager only keep a maximal offset which i have marked，then if i don't mark offsets in order，it may commit the intermediate offsets which i not mark.

for example，there are three messages which offsets are 1、2、3，I mark the offset 1、3，but not the offset 2，partitionOffsetManager should commit offset 1 to kafka，but offset 3 is committed.

**Comment by panamafrancis** [comment] 2019-04-01 17:06
i believe this is the intended behaviour of kafka partitions, you can't speculatively process messages and commit their offsets out of order. 

If you want to improve throughput you increase the number of partitions but maintain a maximum 1:1 ratio of partitions to consumers. i.e. you can't have 1 partition with 2 consumers.

if you can't guarantee the validity of each message but want to process them later you could implement a dead letter queue where you push unprocessed messages to.

**Comment by panamafrancis** [comment] 2019-04-01 17:06
I would vote to close this issue.

**Closed** 2019-08-22 20:02 UTC
Labels: question
