### ISSUE TITLE
Snappy Library Has Moved To A New Location

### ISSUE THREAD

**Issue by kkevinchou** [Shopify/sarama#462] opened 2015-06-02 00:14 UTC
It has moved to: https://github.com/google/snappy

Trying to run godep restore generates the following error:

`package code.google.com/p/snappy-go/snappy: unable to detect version control system for code.google.com/ path`

**Comment by eapache** [comment] 2015-06-02 00:48
Duplicate of #456, already fixed in master and version 1.4.2

**Closed by eapache** 2015-06-02 00:48 UTC
Labels: duplicate
