### ISSUE TITLE
Why CURRENT-OFFSET NOT change when AutoCommit disabled?

### ISSUE THREAD

**Issue by lqiz** [Shopify/sarama#1671] opened 2020-04-17 05:26 UTC
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| 2.6.2 |1.1.0  |1.2  |

##### Problem Description

1. use the example of [consumer group|https://github.com/Shopify/sarama/tree/master/examples/consumergroup]
2. Disable the AutoCommit by this
config.Consumer.Offsets.AutoCommit.Enable = false
3. Show status via ./kafka-consumer-groups.sh  --describe --group XX  --bootstrap-server XX
TOPIC      PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG           CONSUMER-ID

4. Why CURRENT-OFFSET  never changed? It will change when AutoCommit enabled.

**Comment by crazytaxi824** [comment] 2020-05-07 02:07
because you are not be able to Commit manually,
#1570

**Comment by dnwe** [comment] 2020-06-24 05:10
Dupe of #1570

**Closed by dnwe** 2020-06-24 05:10 UTC
