### ISSUE TITLE
Observing issues with old version of klauspost/compress used in sarama, bump up the version

### ISSUE THREAD

**Issue by subbu05** [Shopify/sarama#2032] opened 2021-09-18 17:28 UTC
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|v1.29.0
v1.29.1  | 2.x | 1.16 |

##### Problem Description
When I ran to check memory leaks I found following issue
bash-3.2$ go test 
testing: warning: no tests to run
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 19 in state chan receive, with github.com/klauspost/compress/zstd.(*blockDec).startDecoder on top of the stack:
goroutine 19 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000201e10)
        /Users/s/go/pkg/mod/github.com/klauspost/compress@v1.12.2/zstd/blockdec.go:215 +0x149
created by github.com/klauspost/compress/zstd.newBlockDec
        /Users/s/go/pkg/mod/github.com/klauspost/compress@v1.12.2/zstd/blockdec.go:118 +0x173

**Comment by dnwe** [comment] 2021-09-22 13:22
Dupe of https://github.com/Shopify/sarama/issues/2029

**Closed by dnwe** 2021-09-22 13:22 UTC
